env:
  global:
    secure: Rty+nwOfl9ZBJh4jPF1OvqeTfh7QExlSZHXRHe1nkDF8Iyee3lqMA6qytr2QD/qgmxqJwGfc/nDrK30/ksmgQXW0N2tFuWSFDFSK5zRo+8/nJF+yYIWKRQOlS4WmbtHZxFc4+Hh6zwqcfMW4Q8zbnXzxSsfwNuabcbNUVOx6wlpRLHrKQCFlkEXp7ton9nYGvRmVDWyBIY0nwPnw4ZyjH/2VEDemq7yYtRC9+yUhU2eLaiQZH8lykb65OgEP2rdluGGnRED7ff7sqEiQVw/LGWRtFRj0o6g+OQlvwcCss+iHuF2TpC26MOHXrVJOnk978uyug3F0BIDvM4MMOw+EujokAdjCbHV7y/YTOHFZ9GuBFVBzn1Wogt14RO85NzxWnchJ3nIygJEcVQxnp4N4zl7Gh5NRktOJ2O3OATOBEy0CyxY8fiF9/xz9L4wpFmxIm9T4nLZmmqlvKUHZ48GrssknJQeRrpWryMfXB9qAuWV/pPz498I0B19WOR/pmrpGX6dlHsJqQFELc16TNIBxJiHRy8tHeLR7Cq5lxEjzgwOMiQjiVUoF3UgAJWRu8qgVuJxJAg7tWAhVi2Pcj0L6OpEdAqY2fNrse+Owrrmn/SjAz1W2k2aepDPyPOqC8EKcGRwWfVgxwF8Fx7S48wDMoCpIFfj2g46a0gDJ+TqNBD0=

script:
  - ./deploy
